# General
name: JuYeong Jeong blog
description: "NHNEnt, Software, Developer"
url: http://juyeongjeong.github.io/

markdown: kramdown
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: juyeongJung
twitter: yourusername
github: JuYeongJeong
google: +yourusername

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"